# 查看生效的配置
#debug: true

server:
  port: 8085

spring:
  #服务名称，springcloud中使用
  application:
    name: service-edu
  #开发环境  dev、test、pro
  profiles:
    active: dev
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fshing
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatisplus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl