# 查看生效的配置
#debug: true

server:
  port: 8085

spring:
  #服务名称，springcloud中使用
  application:
    name: service-edu
  #开发环境  dev、test、pro
  profiles:
    active: dev
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fshing
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#mybatisplus日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:com/atguigu/eduservice/mapper/xml/*.xml

#开启熔断机制
feign:
  hystrix:
    enabled: false
#设置hystrix超市时间，默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
